import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

// const openSans = Open_Sans({
//   subsets: ["latin"],
//   variable: "--font-open-sans",
// });

const agrandir = localFont({
  src: "../fonts/PPAgrandir-Variable.woff2",
  display: "swap",
  variable: "--font-agrandir",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(agrandir.variable)}>{children}</body>
    </html>
  );
}
